apiVersion: appsody.dev/v1beta1
kind: AppsodyApplication
metadata:
  annotations:
    commit.image.appsody.dev/author: dannil@dk.ibm.com <danniluong@gmail.com>
    commit.image.appsody.dev/committer: dannil@dk.ibm.com <danniluong@gmail.com>
    commit.image.appsody.dev/contextDir: C:\danni-microprofile1
    commit.image.appsody.dev/date: Tue Feb 4 11:01:42 2020 +0100
    commit.image.appsody.dev/message: "13"
    image.opencontainers.org/created: "2020-02-04T23:00:24+01:00"
    image.opencontainers.org/documentation: https://github.com/danniluong/danni-microprofile1
    image.opencontainers.org/revision: d1515feaed7481ede5e603c5c1d207826a70c3a2
    image.opencontainers.org/source: |
      https://github.com/danniluong/danni-microprofile1/tree/master
    image.opencontainers.org/url: https://github.com/danniluong/danni-microprofile1
    stack.appsody.dev/configured: docker.io/appsody/java-microprofile:0.2
    stack.appsody.dev/created: 2019-11-26T15:01:00+0000
    stack.appsody.dev/revision: 697abc712b0ee47832d1016bbf0d1b5d50129338
    stack.appsody.dev/tag: appsody/java-microprofile:0.2.21
  creationTimestamp: null
  labels:
    image.opencontainers.org/title: danni-microprofile1
    stack.appsody.dev/version: 0.2.21
  name: danni-microprofile1
  name-space: danske-bank
spec:
  applicationImage: dev.local/danni-microprofile1
  createKnativeService: false
  expose: true
  livenessProbe:
    failureThreshold: 12
    httpGet:
      path: /health/live
      port: 9080
    initialDelaySeconds: 5
    periodSeconds: 2
  readinessProbe:
    failureThreshold: 12
    httpGet:
      path: /health/ready
      port: 9080
    initialDelaySeconds: 5
    periodSeconds: 2
    timeoutSeconds: 1
  service:
    annotations:
      prometheus.io/scrape: "true"
    port: 9080
    type: NodePort
  stack: java-microprofile
  version: 1.0.0
status: {}
